// This file is automatically generated. Do not edit manually.
// Generated by TypeRegistryBuilder

import 'package:frogsoup_model/frogsoup_model_exports.dart';
import 'package:protobuf/protobuf.dart';

final frogsoupTypeRegistry = TypeRegistry([
  CharacterProto.getDefault(),
  TypingNpcBehaviorProto.getDefault(),
  PromptTargetingNpcBehaviorProto.getDefault(),
  DamageableValueProto.getDefault(),
  FrogsoupLevelProto.getDefault(),
  ItemProto.getDefault(),
  UniformRandomVariableProto.getDefault(),
  NormalRandomVariableProto.getDefault(),
  ConstantRandomVariableProto.getDefault(),
  RoomProto.getDefault(),
  SpriteDisplayProto.getDefault(),
  AnimatedSpriteDisplayProto.getDefault(),
  RotateAnimationDisplayProto.getDefault(),
  WeaponDataProto.getDefault(),
]);
    