import 'dart:async';

import 'package:build/build.dart';
import 'package:glob/glob.dart';

class ExportIndexBuilder extends Builder {
  @override
  Map<String, List<String>> get buildExtensions => {
    r'$lib$': ['frogsoup_model_exports.dart'],
  };

  @override
  FutureOr<void> build(BuildStep buildStep) async {
    // Find all .pb.dart files in the models directory
    final pbFiles = await buildStep.findAssets(Glob('lib/models/**/*.pb.dart')).toList();
    
    // Sort files to ensure consistent output
    pbFiles.sort();
    
    // Generate export statements
    final exportLines = <String>[];
    exportLines.add('// This file is automatically generated. Do not edit manually.');
    exportLines.add('// Generated by ExportIndexBuilder');
    exportLines.add('');
    
    // Add exports for each .pb.dart file
    for (final asset in pbFiles) {
      // Convert asset path to relative import path
      final relativePath = asset.path.replaceFirst('lib/', '');
      exportLines.add("export '$relativePath';");
    }
    
    // Write the generated file
    final outputContent = exportLines.join('\n');
    await buildStep.writeAsString(
      AssetId(buildStep.inputId.package, 'lib/frogsoup_model_exports.dart'),
      outputContent,
    );
  }
}
